GPnaviServer/GPnaviServer/Controllers/WSController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using GPnaviServer.Models;
using System.IO;
using CsvHelper;
using Microsoft.AspNetCore.Http;
using GPnaviServer.Dtos;
using GPnaviServer.Services;
using AutoMapper;
using System.Text.RegularExpressions;
using GPnaviServer.WebSockets.APIs;
using System.Threading.Tasks;

namespace GPnaviServer.Controllers
{
    [Route("[controller]")]
    public class WSController : Controller
    {
        private IUserService _userService;
        private IUserStatusService _userStatusService;
        private IWorkScheduleVersionService _wsvService;
        private IWorkScheduleService _wsmService;
        private IMapper _mapper;


        public WSController(
            IUserService userService,
            IUserStatusService userStatusService,
            IWorkScheduleVersionService workScheduleVersionService, 
            IWorkScheduleService wsmService, 
            IMapper mapper)
        {
            _userService = userService;
            _userStatusService = userStatusService;
            _wsvService = workScheduleVersionService;
            _wsmService = wsmService;
            _mapper = mapper;
        }

        /// <summary>
        /// 入力チェック
        /// </summary>
        /// <param name="loginId">ログイン者ID</param>
        /// <param name="sessionKey">ログイン者のセッションキー</param>
        /// <returns>バリデーションエラーの場合は真</returns>
        private (bool result, UserStatus status) IsInvalidSession(string loginId, string sessionKey)
        {
            ViewBag.LoginName = "";
            if (!string.IsNullOrEmpty(loginId) && !string.IsNullOrEmpty(loginId))
            {
                var status = _userStatusService.GetById(loginId);
                if (status != null && string.Equals(sessionKey, status.SessionKey))
                {
                    ViewBag.LoginName = _userService.GetById(loginId).LoginName;
                    return (true, status);
                }
            }   

            return (false, null);
        }

        [HttpGet("TimeAggregate")]
        public IActionResult TimeAggregate(string loginId, string sessionKey)
        {
            var (result, status) = IsInvalidSession(loginId,  sessionKey);
            if (result)
            {
                return View("TimeAggregate");
            }

            return View("~/Views/Users/Login.cshtml");
        }

        [HttpGet("DayAggregate")]
        public IActionResult DayAggregate(string loginId, string sessionKey)
        {
            var (result, status) = IsInvalidSession(loginId, sessionKey);
            if (result)
            {
                return View("DayAggregate");
            }

            return View("~/Views/Users/Login.cshtml");
        }

        [HttpGet("upload")]
        public IActionResult Upload(string loginId,string sessionKey)
        {
            var (result, status) = IsInvalidSession(loginId, sessionKey);
            if (result)
            {
                return View("upload", status);
            }

            return View("~/Views/Users/Login.cshtml");
        }


        [HttpPost("uploadws")]
        public async Task<IActionResult> UploadWS(IFormFile file,string LoginId,string SessionKey)
        {

            var (result, userStatus) = IsInvalidSession(LoginId, SessionKey);
            if (!result)
            {
                return View("~/Views/Users/Login.cshtml");
            }

            if (file.Length < 1)
            {
                return View("upload", userStatus);
            }

            try { 
                var config = new CsvHelper.Configuration.Configuration
                {
                    HasHeaderRecord = false,
                    MissingFieldFound = null,
                    IgnoreBlankLines = true,
                };

                using (var streamReader = new StreamReader(file.OpenReadStream()))
                using (var csv = new CsvReader(streamReader, config))
                {
                    IEnumerable<WSCsvRow> wsCsvRow = csv.GetRecords<WSCsvRow>();

                    List<WorkScheduleMaster> wsmList;

                    if (csvValidationWsErr(wsCsvRow, out wsmList))
                    {
                        return View("upload", userStatus);
                    }

                    await _wsmService.UploadAsync(wsmList);

                    ViewBag.Message = String.Format(ApiConstant.INFO_UPLOAD_WS_01, wsmList.Count);

                }
            }
            catch (Exception)
            {
                ViewBag.Message = String.Format(ApiConstant.ERR90);
            }


            return View("upload", userStatus);
        }


        private bool csvValidationWsErr(IEnumerable<WSCsvRow> wsCsvRow, out List<WorkScheduleMaster> wsmList)
        {
            wsmList = new List<WorkScheduleMaster>();

            //スタート時刻のフォーマット
            Regex checktime = new Regex(@"^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$");

            //時間としての分のフォーマット
            Regex checkMinute = new Regex(@"^[0-9]*[1-9][0-9]*$");

            //重要度の値の範囲
            var prioritySet = new HashSet<string>(){ "H", "M", "L" };
            var iconIdSet = new HashSet<string>()
            {
                "0000",
                "0001",
                "0002",
                "0003",
                "0004",
                "0005",
                "0006",
                "0007",
                "0008",
                "0009",
                "0010",
                "0011"
            };

            //休日区分の範囲
            var holidaySet = new HashSet<string>() {ApiConstant.HOLIDAY_FALSE, ApiConstant.HOLIDAY_TRUE};

            //重複判別用wsSetを用意
            var wsSet = new HashSet<WSCsvRow>();

            int line = 0;
            foreach (var ws in wsCsvRow)
            {
                ++line;

                //入力値のチェック
                if (string.IsNullOrWhiteSpace(ws.Start))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR10, line, ApiConstant.START_JP);
                    return true;
                }
                if (!checktime.IsMatch(ws.Start))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR11, line, ApiConstant.START_JP);
                    return true;
                }
                if (ws.Start.Length== ApiConstant.START_LENGTH_MIN)
                {
                    ws.Start = "0" + ws.Start;
                }


                //重複チェック
                if (!wsSet.Add(ws))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR15, line, ApiConstant.WS_KEY_JP);
                    return true;
                }


                if (string.IsNullOrWhiteSpace(ws.Name))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR10, line, ApiConstant.WS_NAME_JP);
                    return true;
                }
                if ( ws.Name.Length > ApiConstant.WS_NAME_LENGTH_MAX)
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR12, line, ApiConstant.WS_NAME_JP, ApiConstant.WS_NAME_LENGTH_MAX);
                    return true;
                }


                if (string.IsNullOrWhiteSpace(ws.ShortName) )
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR10, line, ApiConstant.WS_SHORTNAME_JP);
                    return true;
                }
                if (ws.ShortName.Length > ApiConstant.WS_SHORTNAME_LENGTH_MAX)
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR12, line, ApiConstant.WS_SHORTNAME_JP, ApiConstant.WS_SHORTNAME_LENGTH_MAX);
                    return true;
                }


                if (string.IsNullOrWhiteSpace(ws.Priority))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR10, line, ApiConstant.PRIORITY_JP);
                    return true;
                }
                if ( !prioritySet.Contains(ws.Priority))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR13, line, ApiConstant.PRIORITY_JP);
                    return true;
                }

                if (string.IsNullOrWhiteSpace(ws.IconId))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR10, line, ApiConstant.ICONID_JP);
                    return true;
                }
                if (!iconIdSet.Contains(ws.IconId))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR13, line, ApiConstant.ICONID_JP);
                    return true;
                }

                if (string.IsNullOrWhiteSpace(ws.Time))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR10, line, ApiConstant.WORK_TIME_JP);
                    return true;
                }
                if ( !checkMinute.IsMatch(ws.Time))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR13, line, ApiConstant.WORK_TIME_JP);
                    return true;
                }

                if (string.IsNullOrWhiteSpace(ws.Holiday) )
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR10, line, ApiConstant.HOLIDAY_JP);
                    return true;
                }
                if ( !holidaySet.Contains(ws.Holiday))
                {
                    ViewBag.Message = String.Format(ApiConstant.ERR13, line, ApiConstant.HOLIDAY_JP);
                    return true;
                }

                var wsm = _mapper.Map<WorkScheduleMaster>(ws);
                wsm.Row = line;
                wsmList.Add(wsm);
            }

            return false;
        }

    }

}

GPnaviServer/GPnaviServer/Views/WS/DayAggregate.cshtml
@using GPnaviServer.Models;

@{
    ViewData["Title"] = "日別集計";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />


<div class="container">
    <div class="col-sm-10 col-md-10 col-md-offset-6 mx-auto">
        <h2 style="color: #2952a3;"><img src="~/images/day_title.png" class="img-responsive">&nbsp;日別集計</h2><br />

        @*TODO:PowerBIで集計展示*@

    </div>
</div>

<script>
</script>

GPnaviServer/GPnaviServer/Views/WS/TimeAggregate.cshtml
@using GPnaviServer.Models;

@{
    ViewData["Title"] = "時間帯別集計";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />


<div class="container">
    <div class="col-sm-10 col-md-10 col-md-offset-6 mx-auto">
        <h2 style="color: #2952a3;"><img src="~/images/time_title.png" class="img-responsive">&nbsp;時間帯別集計</h2><br />

        @*TODO:PowerBIで集計展示*@

    </div>
</div>

<script>
</script>

GPnaviServer/GPnaviServer/Views/WS/Upload.cshtml
@using GPnaviServer.Models;

@{
    ViewData["Title"] = "Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />


<div class="container">
    <div class="col-sm-8 col-md-8 col-md-offset-8 mx-auto">

        <h2 style="color: #2952a3;"><img src="~/images/up_title.png" class="img-responsive">&nbsp;アップロード</h2><br />

        <div class="">            
            <label id="dis" style="color: red;">@ViewBag.Message</label><br><br />
        </div>

        <h4>ワークスケジュール</h4><br />
        <form method="post" enctype="multipart/form-data" asp-controller="WS" asp-action="uploadws" id="wsForm">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="ファイルをお選びください" required readonly="" tabindex="10" id="wsFile" style="background: #ffffff">
                <label class="input-group-btn">
                    <span class="btn btn-gray" style="margin-left: 20px;" tabIndex="11">
                        ファイル選択<input type="file" style="display:none" accept="text/csv,.csv,.CSV" name="file" />
                    </span>
                </label>
            </div>
            <div>
                <button class="btn float-right btn-gpnavi" id="uploadws" type="button" tabindex="12">
                    アップロード
                </button>
            </div>
        </form>
        <br /><br /><hr />

        <h4>店員情報</h4><br />
        <form method="post" enctype="multipart/form-data" asp-controller="Users" asp-action="uploaduserdata" id="staffForm">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="ファイルをお選びください" required readonly="" tabindex="13" id="staffFile" style="background: #ffffff">
                <label class="input-group-btn">
                    <span class="btn btn-gray" style="margin-left: 20px;" tabIndex="14">
                        ファイル選択<input type="file" style="display:none" accept="text/csv,.csv,.CSV" name="file" />
                    </span>
                </label>
            </div>
            <div>
                <button class="btn float-right btn-gpnavi" id="uploadstaff" type="button" tabindex="15">
                    アップロード
                </button>
            </div>
        </form>
        <br /><br /><hr />


    </div>
</div>

<script>

    $(document).on('change', ':file', function () {
        var input = $(this),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.parent().parent().prev(':text').val(label);
    });

    $('#uploadws').click(function () {
        if ($('#wsFile').val().length > 0) {
            $('#wsForm').submit();
        } else {
            //ワークスケジュールCSVファイルを選択してください
            $('#dis').text('@Html.Raw(GPnaviServer.WebSockets.APIs.ApiConstant.ERR90)');
        }
    });

    $('#uploadstaff').click(function () {
        if ($('#staffFile').val().length > 0) {
            $('#staffForm').submit();
        } else {
            //店員情報CSVファイルを選択してください
            $('#dis').text('@Html.Raw(GPnaviServer.WebSockets.APIs.ApiConstant.ERR90)');
        }
    });

    let ENTER_KEY = 13;
    $('.form-control').on('keypress', function (e) {
        if (e.keyCode === ENTER_KEY && $(this).val().length < 1) {
            e.preventDefault();
            $(this).parent().next().children().trigger('click');
        }
    });
    
</script>